apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: backend-ns
  labels:
    app: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: 710281024320.dkr.ecr.ap-northeast-2.amazonaws.com/ingress-kitchen:d1fd02e
        ports:
        - containerPort: 8000
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: backend-cf
              key: BACKEND_PORT
        - name: GUESTBOOK_DB_ADDR
          valueFrom:
            configMapKeyRef:
              name: backend-cf
              key: GUESTBOOK_DB_ADDR
      imagePullSecrets:
      - name: ecr-secret
